version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - retirement-network

  # seed:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   environment:
  #     - PYTHONPATH=/app
  #   command: ./seed.sh
  #   networks:
  #     - retirement-network

  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=${SQL_USER}
  #     - POSTGRES_PASSWORD=${SQL_PASSWORD}
  #     - POSTGRES_DB=${SQL_DATABASE}
  #   env_file:
  #     - .env
  #   networks:
  #     - backend

  # redis:
  #   build:
  #     context: .
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: redis
  #   hostname: redis
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - backend

networks:
  backend:
    driver: 'bridge'
  retirement-network:
    driver: bridge

# volumes:
#   postgres_data: